const servers = [
    {
        id: 1,
        name: 'Auto',
        location: 'Auto',
        latency: 0,
        latencyUnit: 'ms',
        latencyColor: 'green',
    },
    {
        id: 2,
        name: 'US',
        location: 'New York',
        latency: 100,
        latencyUnit: 'ms',
        latencyColor: 'green',
    },
    {
        id: 3,
        name: 'US',
        location: 'Los Angeles',
        latency: 200,
        latencyUnit: 'ms',
        latencyColor: 'yellow',
    },
    {
        id: 4,
        name: 'US',
        location: 'Dallas',
        latency: 300,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 5,
        name: 'US',
        location: 'Miami',
        latency: 400,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 6,
        name: 'US',
        location: 'Chicago',
        latency: 500,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 7,
        name: 'US',
        location: 'Seattle',
        latency: 600,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 8,
        name: 'US',
        location: 'Atlanta',
        latency: 700,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 9,
        name: 'US',
        location: 'San Jose',
        latency: 800,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 10,
        name: 'US',
        location: 'Washington',
        latency: 900,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 11,
        name: 'US',
        location: 'Las Vegas',
        latency: 1000,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 12,
        name: 'US',
        location: 'Phoenix',
        latency: 1100,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 13,
        name: 'US',
        location: 'New Jersey',
        latency: 1200,
        latencyUnit: 'ms',
        latencyColor: 'red',
    },
    {
        id: 14,
        name: 'US',
        location: 'Denver',
        latency: 1300,
        latencyUnit: 'ms',
        latencyColor: 'red',
    }
]

export { servers }